"""daily_turtle_trend_v1 — one correction pass (no signal/rule changes).

Prior run (fixed_one_contract_ES_NQ_55_20) preserved as-is; this script only
fixes the EVALUATION, per the operator's five flagged problems:
  1. ES/NQ used here for signal robustness (R-multiples), not as the executable system.
  2. ES/NQ (and separately MES/MNQ) treated as ONE correlated equity-index bucket:
     trades that overlap in time AND direction between the two instruments are
     weighted 0.5 each (so a simultaneous same-direction pair contributes a
     combined 1.0, not 2.0) rather than summed at full weight.
  3. Results reported in R-multiples (1R = the initial 2*ATR stop distance in
     price terms) so ES/NQ point-value differences cannot distort the signal
     read. Dollar results are reported separately, on MES/MNQ specifically.
  4. Dollar results use the actual micro contract specs (MES $5/pt, MNQ $2/pt),
     not the full-size E-mini values used in the first run.
  5. TradingView continuous-contract adjustment mode was never confirmed by
     this session (see prior report). All dollar results here are marked
     PROVISIONAL on that basis. R-multiples are somewhat, but not fully,
     insulated from roll artifacts (a false breakout signal generated by a
     roll jump would still show up as a real trade in R terms).

No parameters were changed from the frozen 55/20/ATR20/2N rule set.
"""
from __future__ import annotations

import sys
sys.path.insert(0, "research")
from daily_turtle_trend_v1_phase1 import (
    load_bars, simulate, count_quarter_rolls, HOLDOUT_START, STOP_MULT,
)

BEST_YEAR_SHARE_LIMIT = 35.0


def trade_r(t) -> float:
    return t.points() / (STOP_MULT * t.n_at_entry)


def overlaps_same_direction(a, b) -> bool:
    return a.direction == b.direction and a.entry_date <= b.exit_date and b.entry_date <= a.exit_date


def bucket_weight(trades_a, trades_b):
    """0.5 weight for any trade with a same-direction time overlap in the other
    instrument's trade list; 1.0 otherwise. Returns {id(trade): weight}."""
    w = {}
    for t in trades_a:
        w[id(t)] = 0.5 if any(overlaps_same_direction(t, o) for o in trades_b) else 1.0
    for t in trades_b:
        w[id(t)] = 0.5 if any(overlaps_same_direction(t, o) for o in trades_a) else 1.0
    return w


def r_series(trades, weights=None):
    return [(t, trade_r(t) * (weights[id(t)] if weights else 1.0)) for t in trades]


def yearly(pairs):
    by_year = {}
    for t, v in pairs:
        by_year[t.year()] = by_year.get(t.year(), 0.0) + v
    return by_year


def verdict_check(dev_pairs, label):
    total = sum(v for _, v in dev_pairs)
    by_year = yearly(dev_pairs)
    if not by_year or total <= 0:
        ex_best_nonpositive = True
        share = None
        best_year = None
    else:
        best_year, best_val = max(by_year.items(), key=lambda kv: kv[1])
        ex_best = total - best_val
        ex_best_nonpositive = ex_best <= 0
        share = best_val / total * 100
    broken = ex_best_nonpositive or (share is not None and share > BEST_YEAR_SHARE_LIMIT)
    print(f"  [{label}] dev total R={total:.2f}  best_year={best_year} share={share:.1f}%"
          if share is not None else f"  [{label}] dev total R={total:.2f} (non-positive or no data)")
    print(f"  [{label}] ex-best-year non-positive: {ex_best_nonpositive}  "
          f"share>{BEST_YEAR_SHARE_LIMIT}%: {share is not None and share > BEST_YEAR_SHARE_LIMIT}  "
          f"=> {'BROKEN' if broken else 'passes gate (no higher than PROMISING BUT UNPROVEN)'}")
    return broken


def print_split(name, pairs):
    if not pairs:
        print(f"    {name}: no trades")
        return
    total = sum(v for _, v in pairs)
    by_year = yearly(pairs)
    print(f"    {name}: n={len(pairs)} total_R={total:.2f}")
    print(f"      by year (R): " + ", ".join(f"{y}:{v:.2f}" for y, v in sorted(by_year.items())))


if __name__ == "__main__":
    print("################ PART A — signal robustness, R-multiples, ES1!/NQ1! (long history) ################")
    es_bars = load_bars("docs/CME_MINI_ES1!, 1D (2).csv")
    nq_bars = load_bars("docs/CME_MINI_NQ1!, 1D (2).csv")
    es_trades = simulate("ES1!", es_bars)
    nq_trades = simulate("NQ1!", nq_bars)

    w = bucket_weight(es_trades, nq_trades)
    overlap_count = sum(1 for t in es_trades if w[id(t)] == 0.5) + sum(1 for t in nq_trades if w[id(t)] == 0.5)
    print(f"ES1! trades: {len(es_trades)}  NQ1! trades: {len(nq_trades)}  "
          f"same-direction time-overlapping trades (bucket-capped): {overlap_count}")

    es_r = r_series(es_trades, w)
    nq_r = r_series(nq_trades, w)
    bucket_r = es_r + nq_r

    for label, pairs_all in [("ES1! only", es_r), ("NQ1! only", nq_r), ("Bucket (ES+NQ, overlap-capped)", bucket_r)]:
        print(f"\n-- {label} --")
        dev = [(t, v) for t, v in pairs_all if t.exit_date < HOLDOUT_START]
        hold = [(t, v) for t, v in pairs_all if t.exit_date >= HOLDOUT_START]
        print_split("development (<2025)", dev)
        print_split("holdout (2025-2026)", hold)
        print_split("full period", pairs_all)

    print("\n=== VERDICT GATE (applied to bucket-combined ES+NQ development R, the signal-robustness evidence) ===")
    dev_bucket = [(t, v) for t, v in bucket_r if t.exit_date < HOLDOUT_START]
    broken = verdict_check(dev_bucket, "ES+NQ bucket dev")

    print("\n\n################ PART B — executable cost check, MES1!/MNQ1! (micro, provisional re: roll-adjustment) ################")
    print("NOTE: TradingView continuous-contract adjustment mode (back-adjusted vs raw) was never confirmed.")
    print("All dollar figures below are PROVISIONAL on that basis.\n")

    import daily_turtle_trend_v1_phase1 as base
    base.COMMISSION_PER_SIDE = 1.25  # micro commission assumption, stated explicitly
    base.INSTRUMENTS["MES1!"] = {"file": "docs/CME_MINI_MES1!, 1D (2).csv", "point_value": 5.0, "tick": 0.25}
    base.INSTRUMENTS["MNQ1!"] = {"file": "docs/CME_MINI_MNQ1!, 1D.csv", "point_value": 2.0, "tick": 0.25}

    mes_bars = load_bars("docs/CME_MINI_MES1!, 1D (2).csv")
    mnq_bars = load_bars("docs/CME_MINI_MNQ1!, 1D.csv")
    mes_trades = simulate("MES1!", mes_bars)
    mnq_trades = simulate("MNQ1!", mnq_bars)
    wm = bucket_weight(mes_trades, mnq_trades)
    m_overlap = sum(1 for t in mes_trades if wm[id(t)] == 0.5) + sum(1 for t in mnq_trades if wm[id(t)] == 0.5)
    print(f"MES1! trades: {len(mes_trades)}  MNQ1! trades: {len(mnq_trades)}  "
          f"same-direction time-overlapping trades (bucket-capped): {m_overlap}\n")

    def dollar_summary(label, trades, point_value, weights=None):
        if not trades:
            print(f"  {label}: 0 trades")
            return
        pnls = [t.pnl(point_value, count_quarter_rolls(t.entry_date, t.exit_date)) * (weights[id(t)] if weights else 1.0)
                for t in trades]
        net = sum(pnls)
        wins = sum(p for p in pnls if p > 0)
        losses = -sum(p for p in pnls if p <= 0)
        pf = wins / losses if losses > 0 else float("inf")
        by_year = {}
        for t, p in zip(trades, pnls):
            by_year[t.year()] = by_year.get(t.year(), 0.0) + p
        print(f"  {label} [PROVISIONAL]: n={len(trades)} net=${net:,.0f} PF={pf:.2f}")
        print(f"    by year: " + ", ".join(f"{y}:${v:,.0f}" for y, v in sorted(by_year.items())))

    dollar_summary("MES1! (1 micro contract)", mes_trades, 5.0)
    dollar_summary("MNQ1! (1 micro contract)", mnq_trades, 2.0)
    print("  -- bucket-combined (overlap-capped at 0.5x each when same-direction & concurrent) --")
    combined_bucket_trades = [(t, 5.0, wm) for t in mes_trades] + [(t, 2.0, wm) for t in mnq_trades]
    net_bucket = sum(t.pnl(pv, count_quarter_rolls(t.entry_date, t.exit_date)) * wgt[id(t)]
                     for t, pv, wgt in combined_bucket_trades)
    print(f"  MES+MNQ bucket net (provisional): ${net_bucket:,.0f}")

    print(f"\n\n################ FINAL VERDICT ################")
    print("BROKEN" if broken else "No higher than PROMISING BUT UNPROVEN")
