"""Post-epoch evidence keeps its provenance across a deploy.

The check compared every post-epoch row's `generating_git_sha` against the LIVE
release alone, so promoting a new release retroactively marked correctly-stamped
rows as a provenance defect. On 2026-09-07 two deploys turned 7 honest
`vwap_hold` rows — each stamped `73bffb1c776d`, the release that actually
produced them, each carrying `provenance_status` — into a BLOCKED finding
without a byte of evidence changing.

A row generated by an EARLIER release this box genuinely ran is honest evidence
that predates the deploy. A row stamped with a SHA that was never deployed here
is still a real defect and must still block. The watcher is git-free at runtime,
so the release history comes from the immutable release directories on disk.
"""
from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

WATCHER_DIR = Path(__file__).parent.parent / "ops" / "afs_watcher"

LIVE = "2a58615b1c7edecb22e20f8e3cf4e5e697108994"
PRIOR = "73bffb1c776d8585086d1f9c915da633e7ec69fb"
OLDER = "431154042f86ccd2ec1bd9b897286c896b6b1893"
NEVER_DEPLOYED = "dead00beef11cafe2233445566778899aabbccdd"


def _load_watcher():
    if str(WATCHER_DIR) not in sys.path:
        sys.path.insert(0, str(WATCHER_DIR))
    spec = importlib.util.spec_from_file_location("afs_watcher_release_sha", WATCHER_DIR / "watcher.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


w = _load_watcher()


def _releases(tmp_path: Path) -> Path:
    """Build a releases root shaped like the box's, return the live release dir."""
    root = tmp_path / "afs-releases"
    root.mkdir()
    live = root / f"{LIVE[:12]}-20260907-183059"
    live.mkdir()
    (root / f"{PRIOR[:12]}-20260905-195814").mkdir()
    (root / f"{OLDER[:12]}-20260907-181947").mkdir()
    (root / "legacy-20260701-223000").mkdir()          # not a SHA — ignored
    (root / f"{PRIOR}").mkdir()                        # full-SHA dir (older style)
    (root / "some-file.tgz").write_text("x", encoding="utf-8")  # not a dir — ignored
    return live


def test_known_release_shas_reads_the_release_dirs(tmp_path):
    known = w.known_release_shas(_releases(tmp_path))
    assert LIVE[:12] in known
    assert PRIOR[:12] in known
    assert OLDER[:12] in known
    assert not any(k.startswith("legacy") for k in known)
    assert NEVER_DEPLOYED[:12] not in known


def test_known_release_shas_is_empty_without_a_release_dir():
    assert w.known_release_shas(None) == set()


def test_row_from_an_earlier_release_is_accepted(tmp_path, monkeypatch):
    """The exact 2026-09-07 production case: 73bffb1 rows under a 2a58615 release."""
    monkeypatch.setattr(w, "RELEASE_SHA", LIVE)
    known = w.known_release_shas(_releases(tmp_path))
    assert w.sha_is_known_release(PRIOR, known) is True
    assert w.sha_is_known_release(OLDER, known) is True


def test_live_release_sha_is_accepted_even_with_no_dirs(tmp_path, monkeypatch):
    monkeypatch.setattr(w, "RELEASE_SHA", LIVE)
    assert w.sha_is_known_release(LIVE, set()) is True
    assert w.sha_is_known_release(LIVE[:12], set()) is True


def test_sha_never_deployed_here_still_blocks(tmp_path, monkeypatch):
    """The guard must not become a rubber stamp."""
    monkeypatch.setattr(w, "RELEASE_SHA", LIVE)
    known = w.known_release_shas(_releases(tmp_path))
    assert w.sha_is_known_release(NEVER_DEPLOYED, known) is False


def test_short_or_empty_sha_is_rejected(tmp_path, monkeypatch):
    monkeypatch.setattr(w, "RELEASE_SHA", LIVE)
    known = w.known_release_shas(_releases(tmp_path))
    for junk in ("", "abc", "73bffb1", "            "):
        assert w.sha_is_known_release(junk, known) is False


def test_short_prefix_cannot_match_a_longer_unrelated_sha(tmp_path, monkeypatch):
    """A 12-char prefix matches its own release, not a different one."""
    monkeypatch.setattr(w, "RELEASE_SHA", LIVE)
    known = w.known_release_shas(_releases(tmp_path))
    assert w.sha_is_known_release(PRIOR[:12], known) is True
    assert w.sha_is_known_release("ffffffffffff", known) is False


# ── the durable history file ────────────────────────────────────────────────
# The releases root is a ROLLING WINDOW, not a history: the deploy keeps only the
# most recent few directories. On 2026-09-07 three promotes inside thirty minutes
# pruned the 73bffb1 directory and this check went BLOCKED again, because the SHA
# its rows carried was no longer on disk. The history file is never pruned.

def test_history_file_supplies_a_pruned_release(tmp_path, monkeypatch):
    """The exact regression: the SHA is gone from disk but present in history."""
    monkeypatch.setattr(w, "RELEASE_SHA", LIVE)
    monkeypatch.setattr(w, "RELEASE_HISTORY", tmp_path / "release_history.txt")
    (tmp_path / "release_history.txt").write_text(
        f"# promoted releases\n{PRIOR}\n{OLDER}\n", encoding="utf-8"
    )
    root = tmp_path / "afs-releases"
    root.mkdir()
    live = root / f"{LIVE[:12]}-20260907-184839"
    live.mkdir()  # PRIOR deliberately absent from disk — pruned
    known = w.known_release_shas(live)
    assert PRIOR in known          # history stores the full SHA
    assert w.sha_is_known_release(PRIOR, known) is True
    assert w.sha_is_known_release(PRIOR[:12], known) is True


def test_history_file_absent_is_not_an_error(tmp_path, monkeypatch):
    monkeypatch.setattr(w, "RELEASE_HISTORY", tmp_path / "does_not_exist.txt")
    assert w.release_history_shas(tmp_path / "does_not_exist.txt") == set()
    assert w.known_release_shas(None) == set()


def test_history_file_ignores_comments_blanks_and_junk(tmp_path):
    f = tmp_path / "h.txt"
    f.write_text(
        f"# a comment\n\n{PRIOR}\n   \nnot-a-sha\nzz\n{OLDER}  20260907-181947\n",
        encoding="utf-8",
    )
    got = w.release_history_shas(f)
    assert got == {PRIOR, OLDER}


def test_history_and_disk_are_unioned(tmp_path, monkeypatch):
    monkeypatch.setattr(w, "RELEASE_SHA", LIVE)
    hist = tmp_path / "h.txt"
    hist.write_text(PRIOR + "\n", encoding="utf-8")
    monkeypatch.setattr(w, "RELEASE_HISTORY", hist)
    live = _releases(tmp_path)
    known = w.known_release_shas(live)
    assert PRIOR in known                          # from history
    assert OLDER[:12] in known                     # from disk
    assert NEVER_DEPLOYED[:12] not in known


def test_history_file_cannot_whitelist_an_undeployed_sha_implicitly(tmp_path, monkeypatch):
    """Only SHAs actually written to the history are accepted — no wildcards."""
    monkeypatch.setattr(w, "RELEASE_SHA", LIVE)
    hist = tmp_path / "h.txt"
    hist.write_text(PRIOR + "\n", encoding="utf-8")
    monkeypatch.setattr(w, "RELEASE_HISTORY", hist)
    known = w.known_release_shas(None)
    assert w.sha_is_known_release(NEVER_DEPLOYED, known) is False
