"""Post-epoch evidence keeps its provenance across a deploy.

The check compared every post-epoch row's `generating_git_sha` against the LIVE
release alone, so promoting a new release retroactively marked correctly-stamped
rows as a provenance defect. On 2026-09-07 two deploys turned 7 honest
`vwap_hold` rows — each stamped `73bffb1c776d`, the release that actually
produced them, each carrying `provenance_status` — into a BLOCKED finding
without a byte of evidence changing.

A row generated by an EARLIER release this box genuinely ran is honest evidence
that predates the deploy. A row stamped with a SHA that was never deployed here
is still a real defect and must still block. The watcher is git-free at runtime,
so the release history comes from the immutable release directories on disk.
"""
from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

WATCHER_DIR = Path(__file__).parent.parent / "ops" / "afs_watcher"

LIVE = "2a58615b1c7edecb22e20f8e3cf4e5e697108994"
PRIOR = "73bffb1c776d8585086d1f9c915da633e7ec69fb"
OLDER = "431154042f86ccd2ec1bd9b897286c896b6b1893"
NEVER_DEPLOYED = "dead00beef11cafe2233445566778899aabbccdd"


def _load_watcher():
    if str(WATCHER_DIR) not in sys.path:
        sys.path.insert(0, str(WATCHER_DIR))
    spec = importlib.util.spec_from_file_location("afs_watcher_release_sha", WATCHER_DIR / "watcher.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


w = _load_watcher()


def _releases(tmp_path: Path) -> Path:
    """Build a releases root shaped like the box's, return the live release dir."""
    root = tmp_path / "afs-releases"
    root.mkdir()
    live = root / f"{LIVE[:12]}-20260907-183059"
    live.mkdir()
    (root / f"{PRIOR[:12]}-20260905-195814").mkdir()
    (root / f"{OLDER[:12]}-20260907-181947").mkdir()
    (root / "legacy-20260701-223000").mkdir()          # not a SHA — ignored
    (root / f"{PRIOR}").mkdir()                        # full-SHA dir (older style)
    (root / "some-file.tgz").write_text("x", encoding="utf-8")  # not a dir — ignored
    return live


def test_known_release_shas_reads_the_release_dirs(tmp_path):
    known = w.known_release_shas(_releases(tmp_path))
    assert LIVE[:12] in known
    assert PRIOR[:12] in known
    assert OLDER[:12] in known
    assert not any(k.startswith("legacy") for k in known)
    assert NEVER_DEPLOYED[:12] not in known


def test_known_release_shas_is_empty_without_a_release_dir():
    assert w.known_release_shas(None) == set()


def test_row_from_an_earlier_release_is_accepted(tmp_path, monkeypatch):
    """The exact 2026-09-07 production case: 73bffb1 rows under a 2a58615 release."""
    monkeypatch.setattr(w, "RELEASE_SHA", LIVE)
    known = w.known_release_shas(_releases(tmp_path))
    assert w.sha_is_known_release(PRIOR, known) is True
    assert w.sha_is_known_release(OLDER, known) is True


def test_live_release_sha_is_accepted_even_with_no_dirs(tmp_path, monkeypatch):
    monkeypatch.setattr(w, "RELEASE_SHA", LIVE)
    assert w.sha_is_known_release(LIVE, set()) is True
    assert w.sha_is_known_release(LIVE[:12], set()) is True


def test_sha_never_deployed_here_still_blocks(tmp_path, monkeypatch):
    """The guard must not become a rubber stamp."""
    monkeypatch.setattr(w, "RELEASE_SHA", LIVE)
    known = w.known_release_shas(_releases(tmp_path))
    assert w.sha_is_known_release(NEVER_DEPLOYED, known) is False


def test_short_or_empty_sha_is_rejected(tmp_path, monkeypatch):
    monkeypatch.setattr(w, "RELEASE_SHA", LIVE)
    known = w.known_release_shas(_releases(tmp_path))
    for junk in ("", "abc", "73bffb1", "            "):
        assert w.sha_is_known_release(junk, known) is False


def test_short_prefix_cannot_match_a_longer_unrelated_sha(tmp_path, monkeypatch):
    """A 12-char prefix matches its own release, not a different one."""
    monkeypatch.setattr(w, "RELEASE_SHA", LIVE)
    known = w.known_release_shas(_releases(tmp_path))
    assert w.sha_is_known_release(PRIOR[:12], known) is True
    assert w.sha_is_known_release("ffffffffffff", known) is False
